[build]
  command = "pnpm install --no-frozen-lockfile && pnpm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  PNPM_VERSION = "8.15.6"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

