[build]
  command = "pnpm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--version" # prevents Netlify from running npm install

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
